### ISSUE TITLE
bot gives out gyp error

### ISSUE THREAD

**Issue by devMenna** [LeagueSandbox/IssueBot#47]
when I try npm install it gives out npm error/gyp error "tested on different machines both windows and ubuntu and same problem"

**Comment by MythicManiac** [comment]
This'd likely be expected, given that the bot was last updated in 2019. However there are some pre-built Docker images that should still work, and you can even try running a docker build and see if that works.

You can find the pre-built images here: https://hub.docker.com/r/leaguesandbox/issuebot
